import subprocess
import os
import tempfile
from pathlib import Path

NOTE_NAMES_SHARP = ["c", "cis", "d", "dis", "e", "f", "fis", "g", "gis", "a", "ais", "b"]
KEY_SIG_MAP = {
    0: "c \\major",
    1: "des \\major",
    2: "d \\major",
    3: "ees \\major",
    4: "e \\major",
    5: "f \\major",
    6: "fis \\major",
    7: "g \\major",
    8: "aes \\major",
    9: "a \\major",
    10: "bes \\major",
    11: "b \\major",
}


def midi_to_lilypond_note(pitch: int) -> str:
    """Convert MIDI pitch to LilyPond note name."""
    octave = (pitch // 12) - 1
    note_name = NOTE_NAMES_SHARP[pitch % 12]

    # LilyPond: c' = C4 (MIDI 60), c'' = C5, c = C3, c, = C2
    lily_octave = octave - 3  # relative to LilyPond's middle reference
    if lily_octave > 0:
        note_name += "'" * lily_octave
    elif lily_octave < 0:
        note_name += "," * abs(lily_octave)

    return note_name


def quantize_duration(duration_sec: float, tempo: int) -> str:
    """Convert a duration in seconds to a LilyPond duration string."""
    beat_duration = 60.0 / tempo  # seconds per beat

    beats = duration_sec / beat_duration

    if beats >= 3.5:
        return "1"
    elif beats >= 2.5:
        return "2."
    elif beats >= 1.5:
        return "2"
    elif beats >= 1.0:
        return "4"
    elif beats >= 0.5:
        return "8"
    elif beats >= 0.25:
        return "16"
    else:
        return "16"


def generate_sheet_music_pdf(midi_data: dict, output_path: str):
    """Generate a PDF piano sheet music from MIDI data using LilyPond."""
    notes = midi_data["notes"]
    tempo = midi_data["tempo"]
    time_sig = midi_data["timeSignature"]
    key_sig = midi_data.get("keySignature", 0)

    # Split into treble (>= 60 / C4) and bass (< 60)
    treble_notes = [n for n in notes if n["pitch"] >= 60]
    bass_notes = [n for n in notes if n["pitch"] < 60]

    def notes_to_lilypond(note_list: list, max_notes: int = 200) -> str:
        if not note_list:
            return "r1"  # whole rest

        lily_notes = []
        for n in note_list[:max_notes]:
            name = midi_to_lilypond_note(n["pitch"])
            dur = quantize_duration(n["duration"], tempo)
            lily_notes.append(f"{name}{dur}")

        return " ".join(lily_notes)

    treble_str = notes_to_lilypond(treble_notes)
    bass_str = notes_to_lilypond(bass_notes)

    key_lily = KEY_SIG_MAP.get(key_sig, "c \\major")

    lilypond_source = f"""\\version "2.24.0"

\\header {{
  title = "Transcribed Piano Sheet Music"
  subtitle = "Generated by MediaKit"
  tagline = "Automatically transcribed from video audio"
}}

\\paper {{
  #(set-paper-size "letter")
  top-margin = 15\\mm
  bottom-margin = 15\\mm
  left-margin = 15\\mm
  right-margin = 15\\mm
}}

\\score {{
  \\new PianoStaff <<
    \\new Staff = "treble" {{
      \\clef treble
      \\key {key_lily}
      \\time {time_sig[0]}/{time_sig[1]}
      \\tempo 4 = {tempo}
      {treble_str}
    }}
    \\new Staff = "bass" {{
      \\clef bass
      \\key {key_lily}
      \\time {time_sig[0]}/{time_sig[1]}
      {bass_str}
    }}
  >>
  \\layout {{ }}
  \\midi {{ }}
}}
"""

    # Try LilyPond first
    try:
        _generate_with_lilypond(lilypond_source, output_path)
        return
    except (FileNotFoundError, RuntimeError):
        pass

    # Fallback: generate PDF with reportlab
    _generate_with_reportlab(midi_data, output_path)


def _generate_with_lilypond(source: str, output_path: str):
    """Generate PDF using LilyPond."""
    with tempfile.TemporaryDirectory() as tmpdir:
        ly_path = os.path.join(tmpdir, "score.ly")
        with open(ly_path, "w") as f:
            f.write(source)

        cmd = [
            "lilypond",
            "--pdf",
            f"--output={tmpdir}",
            ly_path,
        ]

        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)

        pdf_file = os.path.join(tmpdir, "score.pdf")
        if not Path(pdf_file).exists():
            raise RuntimeError(f"LilyPond failed: {result.stderr[:500]}")

        # Copy to output
        import shutil
        shutil.copy2(pdf_file, output_path)


def _generate_with_reportlab(midi_data: dict, output_path: str):
    """Fallback PDF generation using reportlab (basic but works without LilyPond)."""
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas
        from reportlab.lib.units import inch
    except ImportError:
        # If reportlab not available, create a minimal text-based PDF
        _generate_minimal_pdf(midi_data, output_path)
        return

    c = canvas.Canvas(output_path, pagesize=letter)
    width, height = letter

    # Title
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(width / 2, height - 1 * inch, "Piano Sheet Music")

    c.setFont("Helvetica", 12)
    c.drawCentredString(width / 2, height - 1.4 * inch, "Generated by MediaKit")

    # Music info
    y = height - 2 * inch
    c.setFont("Helvetica", 11)
    notes = midi_data["notes"]
    tempo = midi_data["tempo"]
    time_sig = midi_data["timeSignature"]

    NOTE_NAMES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]
    key_name = NOTE_NAMES[midi_data.get("keySignature", 0)]

    c.drawString(1 * inch, y, f"Tempo: {tempo} BPM    Time Signature: {time_sig[0]}/{time_sig[1]}    Key: {key_name} Major")
    y -= 0.3 * inch
    c.drawString(1 * inch, y, f"Total notes detected: {len(notes)}")
    y -= 0.5 * inch

    # Draw staff lines
    treble_notes = [n for n in notes if n["pitch"] >= 60]
    bass_notes = [n for n in notes if n["pitch"] < 60]

    def draw_staff(canvas_obj, x_start, y_pos, label):
        canvas_obj.setFont("Helvetica-Bold", 10)
        canvas_obj.drawString(x_start, y_pos + 0.15 * inch, label)
        for i in range(5):
            line_y = y_pos - i * 0.1 * inch
            canvas_obj.setLineWidth(0.5)
            canvas_obj.line(x_start + 0.6 * inch, line_y, width - 1 * inch, line_y)

    def draw_notes_on_staff(canvas_obj, note_list, x_start, y_pos, max_notes=40):
        if not note_list:
            return
        staff_width = width - 1 * inch - (x_start + 0.6 * inch)
        display_notes = note_list[:max_notes]
        spacing = staff_width / (len(display_notes) + 1)

        for i, note in enumerate(display_notes):
            x = x_start + 0.6 * inch + spacing * (i + 1)
            # Map pitch to vertical position on staff
            pitch = note["pitch"]
            # Rough mapping: each staff line is 0.1 inch apart
            note_offset = ((pitch % 12) / 12.0) * 0.4 * inch
            note_y = y_pos - 0.2 * inch + note_offset
            canvas_obj.setFillColorRGB(0.3, 0.1, 0.6)
            canvas_obj.circle(x, note_y, 3, fill=1)

            # Note name below
            note_name = NOTE_NAMES[pitch % 12]
            octave = (pitch // 12) - 1
            canvas_obj.setFont("Helvetica", 5)
            canvas_obj.setFillColorRGB(0.4, 0.4, 0.4)
            canvas_obj.drawCentredString(x, note_y - 10, f"{note_name}{octave}")
            canvas_obj.setFillColorRGB(0, 0, 0)

    # Treble staff
    draw_staff(c, 1 * inch, y, "Treble")
    draw_notes_on_staff(c, treble_notes, 1 * inch, y)

    y -= 1.2 * inch

    # Bass staff
    draw_staff(c, 1 * inch, y, "Bass")
    draw_notes_on_staff(c, bass_notes, 1 * inch, y)

    y -= 1.5 * inch

    # Note list
    c.setFont("Helvetica-Bold", 12)
    c.drawString(1 * inch, y, "Detected Notes (first 60):")
    y -= 0.3 * inch
    c.setFont("Courier", 8)

    for i, note in enumerate(notes[:60]):
        if y < 1 * inch:
            c.showPage()
            y = height - 1 * inch
            c.setFont("Courier", 8)

        note_name = NOTE_NAMES[note["pitch"] % 12]
        octave = (note["pitch"] // 12) - 1
        c.drawString(
            1 * inch,
            y,
            f"{note_name}{octave:<4}  Start: {note['startTime']:.2f}s  Duration: {note['duration']:.2f}s  Velocity: {note['velocity']}",
        )
        y -= 0.18 * inch

    c.save()


def _generate_minimal_pdf(midi_data: dict, output_path: str):
    """Absolute minimal PDF generation without any extra dependencies."""
    notes = midi_data["notes"]
    NOTE_NAMES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]

    lines = [
        "Piano Sheet Music - Generated by MediaKit",
        f"Tempo: {midi_data['tempo']} BPM",
        f"Time Signature: {midi_data['timeSignature'][0]}/{midi_data['timeSignature'][1]}",
        f"Total notes: {len(notes)}",
        "",
        "Treble (Right Hand):",
    ]

    for n in [n for n in notes if n["pitch"] >= 60][:50]:
        name = NOTE_NAMES[n["pitch"] % 12]
        octave = (n["pitch"] // 12) - 1
        lines.append(f"  {name}{octave} at {n['startTime']:.2f}s (dur: {n['duration']:.2f}s)")

    lines.append("")
    lines.append("Bass (Left Hand):")
    for n in [n for n in notes if n["pitch"] < 60][:50]:
        name = NOTE_NAMES[n["pitch"] % 12]
        octave = (n["pitch"] // 12) - 1
        lines.append(f"  {name}{octave} at {n['startTime']:.2f}s (dur: {n['duration']:.2f}s)")

    text = "\n".join(lines)

    # Minimal valid PDF
    content = text.encode("latin-1", errors="replace")
    stream = (
        b"%PDF-1.4\n"
        b"1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n"
        b"2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n"
        b"3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]"
        b"/Contents 4 0 R/Resources<</Font<</F1 5 0 R>>>>>>endobj\n"
        b"5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Courier>>endobj\n"
    )

    # Build text stream
    text_ops = b"BT /F1 9 Tf 72 750 Td 12 TL\n"
    for line in lines[:70]:
        safe = line.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
        text_ops += f"({safe}) '\n".encode("latin-1", errors="replace")
    text_ops += b"ET"

    stream_obj = f"4 0 obj<</Length {len(text_ops)}>>stream\n".encode()
    stream_obj += text_ops + b"\nendstream\nendobj\n"

    pdf = stream + stream_obj
    xref_pos = len(pdf)
    pdf += b"xref\n0 6\n"
    pdf += b"0000000000 65535 f \n"
    pdf += b"0000000009 00000 n \n"
    pdf += b"0000000058 00000 n \n"
    pdf += b"0000000115 00000 n \n"
    pdf += f"{len(stream):010d} 00000 n \n".encode()
    pdf += b"0000000300 00000 n \n"
    pdf += f"trailer<</Size 6/Root 1 0 R>>\nstartxref\n{xref_pos}\n%%EOF".encode()

    with open(output_path, "wb") as f:
        f.write(pdf)
